service: redditorchat

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    OPENAI_API_KEY: ${ssm:/redditorchat/OPENAI_API_KEY}
    REDDIT_CLIENT_ID: ${ssm:/redditorchat/REDDIT_CLIENT_ID}
    REDDIT_CLIENT_SECRET: ${ssm:/redditorchat/REDDIT_CLIENT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource:
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/redditorchat/*

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /initialize-chat
          method: post
          cors:
            origin: 'https://redditorchat-git-main-nick-tittertons-projects.vercel.app,https://redditorchat.vercel.app,http://localhost:3000'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /chat
          method: post
          cors:
            origin: 'https://redditorchat-git-main-nick-tittertons-projects.vercel.app,https://redditorchat.vercel.app,http://localhost:3000'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false